apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft232h-runner
  labels:
    app: ft232h
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft232h
  template:
    metadata:
      labels:
        app: ft232h
      annotations:
        # unique hash of the configmap 
        # changes when the configmap changes
        configHash: "2544c5cf422921de8d8307dbe120a35fb84ec408efe111c270adadc5163d2ce5"
    spec:
      containers:
      - name: point
        image: mak3r/ft232h:v0.0.4
        imagePullPolicy: Always
        command: ["python", "gesture.py"]
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        volumeMounts:
        - mountPath: /dev
          name: dev
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: config
        configMap:
          name: gesture-config
          items:
          - key: "gesture.conf"
            path: "gesture.conf"
